### ISSUE TITLE
smapp

### ISSUE THREAD

**Issue by diabolicdesigns** [xeliuqa/SM-Monitor#18]
This does not appear to work in smapp as the ip address for grpc-private-listener in node-config.json gets reset to 127.0.0.1 at launch.

**Comment by Stizerg** [comment]
> This does not appear to work in smapp as the ip address for grpc-private-listener in node-config.json gets reset to 127.0.0.1 at launch.

You need to edit node-config.7c8cef2b.json

**Comment by diabolicdesigns** [comment]
Ok, how should the node-config.7c8cef2b.json look? Like this?

{
  "smeshing": {
    "smeshing-opts": {
      "smeshing-opts-datadir": "S:\\SMH01",
      "smeshing-opts-maxfilesize": 2147483648,
      "smeshing-opts-numunits": 107,
      "smeshing-opts-provider": 1,
      "smeshing-opts-compute-batch-size": 1048576
    },
    "smeshing-coinbase": "Wallet Address",
    "smeshing-proving-opts": {
      "smeshing-opts-proving-nonces": 128,
      "smeshing-opts-proving-threads": 10
    },
    "smeshing-start": true,
    "grpc-private-listener": 0.0.0.0:9093
  }
}

**Comment by Stizerg** [comment]
{
    "api": {
        "grpc-public-services": ["debug", "global", "mesh", "node", "transaction", "activation"],
        "grpc-public-listener": "0.0.0.0:9092",
        "grpc-private-services": ["smesher", "admin"],
        "grpc-private-listener": "0.0.0.0:9093",
        "grpc-json-listener": "0.0.0.0:9094"
    },
    "smeshing": {
        "smeshing-opts": {
            "smeshing-opts-datadir": "/home/stizerg/post/7c8cef2b"
        }
    }
}

my Smapp only for wallet, but it works for monitor

**Comment by diabolicdesigns** [comment]
This issue persists for connecting to smapp nodes unless it is the node you run the monitor on. I have rechecked the sm-monitor config, as well as the node-config.7c8cef2b.json. I have also completely shut off the firewall ensuring that all traffic is allowed. and all nodes/pc's have common credentials.
in one machine I have both a smapp node and a go-spacemesh (CLI) node (using different ports), no issue connecting to go-spacemesh (CLI) node.

![image](https://github.com/xeliuqa/SM-Monitor/assets/33529618/c24bc413-6e48-46fb-a3d6-a3ef2d143fb6)

SM-Monitor Config:
![image](https://github.com/xeliuqa/SM-Monitor/assets/33529618/aa4aaad0-dd83-4696-894a-f268de35c8e3)

node-config.7c8cef2b.json (Same for smapp node2 and smapp node 3):
![image](https://github.com/xeliuqa/SM-Monitor/assets/33529618/f6826dbd-1876-4633-a312-2ac772351ca5)

Powershell connection test, it's almost like no matter what is in the node-config.7c8cef2b.json it will not respond on 9093 or anyother ports I have tried for grpc-private-listener:
![image](https://github.com/xeliuqa/SM-Monitor/assets/33529618/b7a946ef-f327-4547-96eb-6f8e8429a630)

**Comment by Stizerg** [comment]
Yes, it does the same to me. I didn't worry about it because my Smapp is just for a wallet, all I need to know if it's online and synced. 
I don't know if it even should work as we expect.

**Comment by diabolicdesigns** [comment]
Should this issue be reopened in the interim?

**Comment by xeliuqa** [comment]
Further investigation reveals that this is not a SM-Monitor issue. Smapp is refusing remote connections on `grpc-private-listener` port. I think this is a security feature and not a bug.

**Comment by Stizerg** [comment]
I did more tests and experiments with config, it looks like something hardcoded prevents Smapp to respond. Need to look at the code to find out.

**Comment by xeliuqa** [comment]
i tried some too, smapp gets either `127.0.0.1:port` or `.1::port`
and `context deadline exceeded even at 50 seconds`
