### ISSUE TITLE
Eligible Layers Dsiplay

### ISSUE THREAD

**Issue by diabolicdesigns** [xeliuqa/SM-Monitor#23]
This is not an issue, more of an enhancement request. Would be nice to be able to see what layers each node is eligible for a reward in.
This would would probably only need to be queried once and stored in a variable and not be queried again until either a restart of SM-Monitor or New Epoch.

**Comment by xeliuqa** [comment]
Already been doing that for weeks. Please update your SM-Monitor

**Comment by xeliuqa** [comment]
Or if you mean showing on screen what layer will be next, Thats a feature that we are working on and will require a different menu.
