### ISSUE TITLE
nodeID missing after upgrading to spacemesh 1.4

### ISSUE THREAD

**Issue by radcuman69** [xeliuqa/SM-Monitor#34]
After I updated a couple nodes to 1.4 I noticed the Node ID column is missing.  I'm sure you realize this but was curious when you might have an update to try.

**Comment by xeliuqa** [comment]
Hi, did you try devep branch version?
https://github.com/xeliuqa/SM-Monitor/tree/develop

**Comment by saki2fifty** [comment]
I personally confirmed this works.

**Comment by radcuman69** [comment]
I apologize, I didn't know about the dev branch.  I'll try it now.

Thanks!

**Comment by xeliuqa** [comment]
Nothing to apologise for. Not normal to use Dev branch 😉.
