### ISSUE TITLE
nodeID missing

### ISSUE THREAD

**Issue by auerswaldg** [xeliuqa/SM-Monitor#41]
On latest 4.0.3 level
![image](https://github.com/xeliuqa/SM-Monitor/assets/45207813/17559f70-9319-4813-97d4-1030efb07954)

**Comment by xeliuqa** [comment]
Is this a question or are you just showing the colours?
Idle! (Red) Means post service it's ON but not connected to main node.
Possible reasons, name does not match local.key or wrong port.

**Comment by xeliuqa** [comment]
It seems post service it's not connected to the main node or you are using wrong name. Needs to match local.key

**Comment by auerswaldg** [comment]
This is correct:

Name must match the .key files

Thanks!
