### ISSUE TITLE
Unable to locate export file in linux

### ISSUE THREAD

**Issue by auerswaldg** [xeliuqa/SM-Monitor#42]
Appears it is working fine, but setting $fileFormat = 1, 2 or 3 does not result in any file exported.

**Comment by auerswaldg** [comment]
I believe it is this block and file path, just not sure how to edit
 if ($node.layers) {
                if ($fileFormat -eq 1) {
                    $rewardsTrackApp = @(@{$node.fullkey = $node.layers })
                    Write-Output $rewardsTrackApp | ConvertTo-Json -depth 100 | Out-File -FilePath RewardsTrackApp.tmp -Append

**Comment by xeliuqa** [comment]
Hi, code it's working fine. File will only export if you have any eligibility.

Things to try.
If on windows
Right click all 3 files, properties and unblock.
Restart monitor.

**Comment by auerswaldg** [comment]
Yeah I tried to chmod the files in linux but still no export files

**Comment by xeliuqa** [comment]
JSON goes to same folder as sm-monitor.ps1.
Are you sure you have eligibilities?

**Comment by auerswaldg** [comment]
Yes
![image](https://github.com/xeliuqa/SM-Monitor/assets/45207813/f661d3c2-32c7-4016-8577-96260f3f8eff)

**Comment by xeliuqa** [comment]
Cool.
Stizerg will be online soon and able to help you better. In the meantime can you try giving permission to folder where monitor is?

chmod 777 foldername

**Comment by auerswaldg** [comment]
good grief now I feel silly... Yes it works now with the parent folder 777 too.

Thanks
