### ISSUE TITLE
4.06 Failed to find grpcurl

### ISSUE THREAD

**Issue by auerswaldg** [xeliuqa/SM-Monitor#47]
After moving new sm-monitor to exiting folder get error:

PS /home/baldr/monitor/SM-Monitor> ./sm-monitor.ps1
Error: grpcurl not found.
Press any key to continue ...

**Comment by xeliuqa** [comment]
Error is pretty obvious.
Either put grpcurl.exe in same folder as sm-monitor or check path in sm-config.ps1

**Comment by auerswaldg** [comment]
I don't think it is that obvious.
I am using the same sm-configs.ps1 that I used for v4.05.. so nothing changed there

I am using linux so my path is:
$grpcurl = "grpcurl"    #Set GRPCurl path if not in the same folder.

**Comment by auerswaldg** [comment]
This is the new part that obviously causes issue:
    if (!(Test-Path $grpcurl)) {
        Write-Host "Error: grpcurl not found." -ForegroundColor Red
        Write-Host "Press any key to continue ..."
        $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        exit
    }


Update: Yes commenting out that block allows it to work fine.

**Comment by xeliuqa** [comment]
We'll check it out. Thanks.

**Comment by Stizerg** [comment]
@auerswaldg hi. if you are using Linux long enough you should have known how it works.
Usually grpcurl is installed to /usr/local/bin, so the string in sm-configs.ps1 should be 
$grpcurl = "/usr/local/bin/grpcurl"
or if you copy the file to the same folder as sm-monitor.ps1 it should be 
$grpcurl = "./grpcurl"

**Comment by Stizerg** [comment]
But I think I know the way to make already good experience of Ubuntu users better

**Comment by auerswaldg** [comment]
> @auerswaldg hi. if you are using Linux long enough you should have known how it works. Usually grpcurl is installed to /usr/local/bin, so the string in sm-configs.ps1 should be $grpcurl = "/usr/local/bin/grpcurl" or if you copy the file to the same folder as sm-monitor.ps1 it should be $grpcurl = "./grpcurl"

It would not work with the full path in the field, so I did cp grpcurl to the folder and now it works again with the block uncommented.
