### ISSUE TITLE
Meaning of status percentage

### ISSUE THREAD

**Issue by kiss81** [xeliuqa/SM-Monitor#51]
I have one new node showing a status percentage (25.3%). The node is synced, but it's not (yet) smeshing. What is the meaning of the percentage?

**Comment by xeliuqa** [comment]
Hello, please confirm you are in supervised mode.
If true, and you are generating PoST its how much PoST you generated so far. In this case percentage should be moving up.

**Comment by kiss81** [comment]
> Hello, please confirm you are in supervised mode. If true, and you are generating PoST its how much PoST you generated so far. In this case percentage should be moving up.

Thank you! I already generated  the bin files, but forgot that after verify I had to regenerate some as they were corrupted. Now the go-spacemesh node is doing this. Thank you for making this clear!
